
// TICC.ino - master sketch file
// TICC Time interval Counter based on TICC Shield using TDC7200
//
// Copyright John Ackermann N8UR 2016-2025
// Portions Copyright George Byrkit K9TRV 2016
// Portions Copyright Jeremy McDermond NH6Z 2016
// Licensed under BSD 2-clause license

// 3 October 2025 - version 20250103.1
extern const char SW_VERSION[17] = "20251003.1";
extern const char SW_TAG[6] = "BETA";


/*
 * NOTES FOR FUTURE GENERATIONS
 * 
 * Timestamps are generated by combining a 100 us coarse counter
 * from a clock generated on the TICC board with the output from
 * the TDC-7200 chip.  To be precise, the TDC value is *subtracted*
 * from the coarse counter value (PICstop) that immediately follows
 * the TDC raising its interrupt flag.
 *
 * Math and ranges:
 * - Core state (PICcount, ts in ps) uses 64-bit signed integers to keep
 *   subtraction simple and avoid underflow surprises. 64-bit range 
 *   (±9.22e18) is ample: with 100 µs ticks, PICcount would take 
 *   ~2.9e11 years to overflow.
 *
 * Performance notes:
 *
 * Pairing logic (two‑channel modes):
 * - Each channel sets new_ts_ready when a fresh timestamp is computed.
 * - Interval and 3-Cornered Hat print once per pair when both channels are ready
 *   (A→B order), then clear both flags. This prevents mixing new and old
 *   samples, which can appear as ±1 s artifacts.
 * - Timestamp mode prints in ordered pairs with one-sample latency: two
 *   successive samples (across either channel) form a pair. If both 
 *   channels are present the order is chA then chB; if both are from 
 *   the same channel, that channel is printed twice. Single-channel and 
 *   mismatched-rate cases are handled without timeouts or configuration.
 *
 * 3-Cornered Hat chC synthesis:
 * - chA and chB are printed as timestamps. chC represents (B − A) but 
 *   is synthesized to look like a timestamp by taking channel B's 
 *   seconds and using the signed delta (diffSplit) fractional. This 
 *   avoids discontinuities at crossings and preserves three‑corner‑hat 
 *   compatibility.
 *
 * Printing:
 * - Arduino printf lacks 64‑bit; we avoid floating point. We format 
 *   integer seconds and zero‑padded fractional parts using 32‑bit 
 *   helpers. Each line is buffered then emitted with a single 
 *   Serial.write() for lower overhead.
 * - We use writeln64() (in misc.cpp)to write lines to the serial port.
 *   This function is a wrapper around Serial.write() that ensures
 *   the line is terminated with a newline character.  NOTE: This
 *   wrapper is limited to 64 characters, which is more than sufficient
 *   for all TICC data output formats.
 *
 * Why signed:
 * - We frequently subtract (period = ts − last_ts; interval = B − A). 
 *   Results can be negative; signed avoids underflow and special‑case 
 *   handling.
 */

#include <stdint.h>  // define unint16_t, uint32_t


#include <SPI.h>     // SPI support
#include <EEPROM.h>  // eeprom library

#include "EnableInterrupt.h"  // use faster interrupt library

#include "board.h"            // LED macros and Arduino pin definitions
#include "config.h"           // config and eeprom
#include "tdc7200.h"          // TDC registers and structures
#include "timestamp_utils.h"  // timestamp utility functions
#include "print.h"  // optimized 64-bit printing routines

volatile int64_t PICcount;
int64_t CLOCK_HZ;
int64_t PICTICK_PS;
int64_t CLOCK_PERIOD;
int16_t CAL_PERIODS;
int16_t WRAP;
int64_t ticksPerSecond;  // number of coarse ticks per second

config_t config;
MeasureMode MODE, lastMODE;
static uint8_t skip_config_prompt_once = 0;
volatile uint8_t request_restart = 0;
static uint8_t just_restarted = 1;  // Flag to track if we just restarted

// Configuration change tracking
static config_t config_backup;  // Backup of config before changes
uint8_t config_changed = 0;  // Flag indicating config was modified (global for config.cpp access)
static uint8_t config_requested = 0;  // Flag indicating user requested config menu

static tdc7200Channel channels[] = {
  tdc7200Channel('0', ENABLE_0, INTB_0, CSB_0, STOP_0, LED_0),
  tdc7200Channel('1', ENABLE_1, INTB_1, CSB_1, STOP_1, LED_1),
};

void setup() {} // we don't use default setup(), but ticc_setup() below

void ticc_setup() {
  size_t i;
  boolean last_pin;

  pinMode(COARSEint, INPUT);
  pinMode(OUT1, OUTPUT);
  pinMode(OUT2, OUTPUT);
  pinMode(EXT_LED_0, OUTPUT);  // need to set these here; on-board LEDs are set up in TDC7200::setup
  pinMode(EXT_LED_1, OUTPUT);
  pinMode(EXT_LED_CLK, OUTPUT);

  // turn on the LEDs to show we're alive -- use macros from board.h
  SET_LED_0;
  SET_EXT_LED_0;
  SET_LED_1;
  SET_EXT_LED_1;

  /*******************************************
   * Configuration read/change/store
   *******************************************/
  // check or assign serial number
  get_serial_number();

  // if no config stored, or wrong version, restore from default
  if (EEPROM.read(CONFIG_START) != EEPROM_VERSION) {
    // Need to initialize serial at default rate to show message
    Serial.end();  // first close in case we've come here from a break
    Serial.begin(115200);  // Use default baud rate for initial message
    delay(1500);
    Serial.flush();
    Serial.println("No config found.  Writing default...");
    eeprom_write_config_default(CONFIG_START);
  }

  // read config and set global vars
  eeprom_read_config();
  lastMODE = config.MODE;

  // start the serial library with configured baud rate
  Serial.end();  // first close in case we've come here from a break
  Serial.begin(config.BAUD_RATE);
  // Allow host CDC/TTY stack to settle to avoid buffered prompts on reconnect
  delay(1500);
  Serial.flush();
  
  // start the SPI library:
  SPI.end();  // first close in case we've come here from a break
  SPI.begin();

  // print banner -- all non-data output lines begin with "#" so they're seen as comments
  Serial.println("# ");
  Serial.println("# TAPR TICC Timestamping Counter");
  Serial.println("# Copyright 2016-2025 N8UR, K9TRV, NH6Z, WA8YWQ");
  Serial.println("# ");
  
  
  Serial.println("#####################");
  Serial.println("# TICC Configuration: ");
  print_config(config);
  Serial.println("#####################");
  Serial.println("# ");

  // get and save config change (skip once after exiting config menu via '#')
  if (!skip_config_prompt_once) {
    // New config system startup check
    Serial.println("# Type any character for config menu");
    Serial.print("# ");
    bool configRequested = false;
    for (int i = 6; i >= 0; --i) {  // wait ~6 sec so user can type something
      delay(250);   Serial.print('.'); if (Serial.available()) { configRequested = true; break; }
      delay(250);   Serial.print('.'); if (Serial.available()) { configRequested = true; break; }
      delay(250);   Serial.print('.'); if (Serial.available()) { configRequested = true; break; }
      delay(250);   Serial.print('.'); if (Serial.available()) { configRequested = true; break; }
    }
    Serial.println();
    while (Serial.available()) { char c = Serial.read(); }   // eat any characters entered before starting config menu
    if (configRequested) {
      backup_config();
      show_config_menu();
      handle_config_change_exit();
    }
  } else {
    skip_config_prompt_once = 0;
  }
  MODE = config.MODE;

  CLOCK_HZ = config.CLOCK_HZ;
  CLOCK_PERIOD = (PS_PER_SEC / CLOCK_HZ);
  PICTICK_PS = config.PICTICK_PS;
  CAL_PERIODS = config.CAL_PERIODS;
  WRAP = config.WRAP;
  ticksPerSecond = PS_PER_SEC / PICTICK_PS;

  for (i = 0; i < ARRAY_SIZE(channels); ++i) {
    // initialize the channels struct variables
    channels[i].totalize = 0;
    channels[i].PICstop = 0;
    channels[i].tof = 0;
    
    // Initialize timestamp structure
    channels[i].timestamp.seconds = 0;
    channels[i].timestamp.picos = 0;
    channels[i].last_timestamp.seconds = 0;
    channels[i].last_timestamp.picos = 0;
    
    channels[i].last_picstop = 0; // Initialize to 0 (will be updated after first measurement)
    channels[i].name = config.NAME[i];
    channels[i].prop_delay = config.PROP_DELAY[i];
    channels[i].time_dilation = config.TIME_DILATION[i];
    channels[i].fixed_time2 = config.FIXED_TIME2[i];
    channels[i].fudge = config.PROP_DELAY[i] + config.FUDGE0[i]; // these config options are additive.

    // Initialize coarse-time cache (always enabled)
    channels[i].last_picstop = 0;
    channels[i].cached_sec = 0;
    channels[i].cached_rem_ticks = 0;

    // set up the chips
    channels[i].tdc_setup();
    channels[i].ready_next();
  }

  update_cached_config(); // Initialize cached config parameters for maximum print performance

  /*******************************************
   * Synchronize multiple TICCs sharing common
   * 10 MHz and 10 kHz clocks.
   *******************************************/
  if (config.SYNC_MODE == 'P') {                  // if we are primary, send sync by sending CLIENT_SYNC (A8) high
    delay(2000);                                  // but first sleep to allow client boards to get ready
    pinMode(CLIENT_SYNC, OUTPUT);                 // set CLIENT_SYNC as output (defaults to input)
    digitalWrite(CLIENT_SYNC, LOW);               // make sure it's low
    delay(1000);                                  // wait a bit in case other boards need to catch up
    last_pin = digitalRead(COARSEint);            // get current state of COARSE_CLOCK
    while (digitalRead(COARSEint) == last_pin) {  // loop until COARSE_CLOCK changes
      delayMicroseconds(5);                       // wait a bit
      if (i <= 50) {                              // should never get above 20 (100us)
        i++;
        if (i == 50) {  // something's probably wrong
          Serial.println("# ");
          Serial.println("# ");
          Serial.println("# No COARSE_CLOCK... is 10 MHz connected?");
        }
      }
    }
    digitalWrite(CLIENT_SYNC, HIGH);  // send sync pulse
  } else {
    Serial.println("# ");
    Serial.println("# ");
    Serial.println("# In secondary mode and waiting for sync...");
  }

  while (!digitalRead(CLIENT_SYNC)) {}               // spin until CLIENT_SYNC asserts
  PICcount = 0;                                      // initialize counter
  enableInterrupt(COARSEint, coarseTimer, FALLING);  // enable counter interrupt
  enableInterrupt(STOP_0, catch_stop0, RISING);      // enable interrupt to catch channel A
  enableInterrupt(STOP_1, catch_stop1, RISING);      // enable interrupt to catch channel B
  digitalWrite(CLIENT_SYNC, LOW);                    // unassert -- results in ~22uS sync pulse
  pinMode(CLIENT_SYNC, INPUT);                       // set back to input just to be neat

  // print header to stdout
  Serial.println("# ");
  switch (config.MODE) {
    case Timestamp:
      Serial.print("# timestamp (seconds with ");
      Serial.print(config.PLACES);
      Serial.println(" decimal places)");
      break;
    case Interval:
      Serial.print("# time interval A->B (seconds with ");
      Serial.print(config.PLACES);
      Serial.println(" decimal places)");
      break;
    case Period:
      Serial.print("# period (seconds with ");
      Serial.print(config.PLACES);
      Serial.println(" decimal places)");
      break;
    case Hat:
      Serial.print("# timestamp ch0, ch1; interval chA->B (seconds with ");
      Serial.print(config.PLACES);
      Serial.println(" decimal places)");
      break;
    case Debug:
      Serial.println("# time1 time2 clock1 cal1 cal2 PICstop tof timestamp");
      break;
    case Binary:
      Serial.println("# Binary Timestamp mode - 12 byte frames:");
      Serial.println("# header (0x55,0xAA), channel (1 byte), PICstop (4 bytes), tof (4 bytes), CRC (1 byte)");
      Serial.println();
      break;
    case Null:
      Serial.println("# null output mode - no data");
      break;
  }  // switch


  // turn the LEDs off
  CLR_LED_0;
  CLR_EXT_LED_0;
  CLR_LED_1;
  CLR_EXT_LED_1;
  CLR_EXT_LED_CLK;

}  // ticc_setup

/****************************************************************/
void loop() {
  ticc_setup();  // initialize and optionally go to config
  while (1) {    // this is the actual loop!

    if ( (Serial.read() == '#') ) {        // direct entry to config menu
      config_requested = 1; // Set flag to enter config at end of current loop iteration
      while (Serial.available()) (void)Serial.read(); // Clear serial buffer (like <enter> from "#<enter>")
    }

    // Ref Clock indicator:
    // Test every 2.5 coarse tick periods for PICcount changes,
    // and turn on EXT_LED_CLK if changes are detected
    static uint32_t last_micros = 0;    // Loop watchdog timestamp
    static int64_t last_PICcount = 0;   // Counter state memory
    static uint8_t ext_clk_led_on = 0;  // LED state cache to avoid redundant writes

    // Reset static variables if we just restarted to prevent false "Reference lost" messages
    if (just_restarted) {
      last_micros = 0;
      last_PICcount = PICcount;  // Initialize with current PICcount value
      ext_clk_led_on = 0;
      just_restarted = 0;  // Clear the flag
      delay(100); // Small delay to allow coarseTimer ISR to start firing
    }

    {
      uint32_t now = micros();
      if ((now - last_micros) > 250) {       // 2.5 ticks at 100 uS/tick
        last_micros = now;                   // Update the watchdog timestamp
        int64_t pc_snapshot;
        noInterrupts(); // protect read from ISR trips
        pc_snapshot = PICcount;
        interrupts();
        if (pc_snapshot != last_PICcount) {  // Has the counter changed since last sampled?
          if (!ext_clk_led_on) {             // turn on only if was off
            SET_EXT_LED_CLK;
            ext_clk_led_on = 1;
          }
          last_PICcount = pc_snapshot;  // Save the current counter state
        } else {
          if (ext_clk_led_on) {  // turn off only if was on
            CLR_EXT_LED_CLK;
            Serial.println("# 10 MHZ Reference lost!");
            Serial.println("# Press any key to restart after reference is restored.");
            ext_clk_led_on = 0;
            // Wait for a key press, then restart (reinitialize on next loop entry)
            while (Serial.available() == 0) { delay(10); }
            (void)Serial.read();
            return;
          }
        }
      }
    } // end of reflock test


    size_t i;
    for (i = 0; i < ARRAY_SIZE(channels); ++i) {

      // No work to do unless intb is low
      if (digitalRead(channels[i].INTB) == 0) {
        // turn LED on -- use board.h macro for speed
        if (i == 0) {
          SET_LED_0;
          SET_EXT_LED_0;
        };
        if (i == 1) {
          SET_LED_1;
          SET_EXT_LED_1;
        };

        /***************************************************************************
         * The algorithm to calculate timestamps is entirely new in the 202509xx
         * firmware.  It uses a mixed-radix accumulator to avoid 64 bit
         * division/modulo operations, which are very expensive in the Arduino 8
         * bit architecture.  In tests with a minimal print routine, this
         * algorithm did 1250 measurements/second on one channel.  (Printing
         * is a major botteneck; see print.cpp for details on how we
         * optimize that.)
         * 
         * Algorithm:
         * 1. Read TDC7200 measurement data (tof = time-of-flight in picoseconds)
         * 2. Calculate delta time since last measurement using coarse counter (PICstop)
         * 3. Apply mixed-radix accumulation: seconds + picos (0..1e12-1 picoseconds)
         * 4. Handle carry/borrow between picos and seconds automatically
         * 
         * - Uses Timestamp64 struct (uint32_t seconds + uint64_t picos) instead of
         * - Incremental delta calculation avoids per-event 64-bit division
         * - Mixed-radix approach eliminates expensive modulo operations
         * - Preserves full picosecond precision (12 decimal places)
         * 
         * Mathematical basis:
         * Absolute timestamp: T_k = PICstop_k * PICTICK_PS - tof_k
         * dcount = delta PICcount ticks since last event
         * Delta between events: deltaT_k = dcount * PICTICK_PS - (tof_k - tof_{k-1})
         * Accumulator: timestamp += deltaT_k (with automatic carry/borrow)
         ***************************************************************************/

        channels[i].last_tof = channels[i].tof;                 // preserve last tof
        channels[i].last_timestamp = channels[i].timestamp;     // preserve last timestamp if needed
        channels[i].tof = channels[i].read();                   // get new tof (absolute per event)
        uint32_t tof_raw = (uint32_t)channels[i].tof;         // local copy for fast reuse

        // Clear TDC INTB immediately to prevent duplicate processing
        channels[i].ready_next();

        // turn LED off (visual feedback that event was processed)
        if (i == 0) {
          CLR_LED_0;
          CLR_EXT_LED_0;
        };
        if (i == 1) {
          CLR_LED_1;
          CLR_EXT_LED_1;
        };

        // High-throughput binary output mode: minimal output for maximum speed
        // Output: PICstop (bottom 4 bytes) + tof (4 bytes) + channel + CRLF
        // Note: PICstop truncated to 32-bit for speed, so holds about 5 days
        // (100 us per tick) before overflow.  User must detect rollover 
        // for full 64-bit timestamp. Binary frames use Ox55,0xAA for framing plus 8 bit CRC
        // This routine can sustain timestamp output at 1080 measurements/second
        // on one channel at 230400 baud.  At 115200 baud, serial output is a
        // bottlenck and maximum throughput is about 1040 measurements/second on
        // one channel.
          
        if (config.MODE == Binary) {
          uint8_t buffer[11];

          // protect this read from ISR trips
          uint32_t picstop_low32;
          noInterrupts();
          picstop_low32 = (uint32_t)channels[i].PICstop;
          interrupts();
          
          // Build buffer: 2 byte header + 4 bytes PICstop + 4 bytes tof + 1 // byte channel + CRC
          uint8_t buf[12];
          buf[0] = 0x55;
          buf[1] = 0xAA;
          buf[2] = channels[i].name;
          buf[3] = (uint8_t)(picstop_low32 & 0xFF);
          buf[4] = (uint8_t)((picstop_low32 >> 8) & 0xFF);
          buf[5] = (uint8_t)((picstop_low32 >> 16) & 0xFF);
          buf[6] = (uint8_t)((picstop_low32 >> 24) & 0xFF);
          buf[7] = (uint8_t)(tof_raw & 0xFF);
          buf[8] = (uint8_t)((tof_raw >> 8) & 0xFF);
          buf[9] = (uint8_t)((tof_raw >> 16) & 0xFF);
          buf[10] = (uint8_t)((tof_raw >> 24) & 0xFF);
          buf[11] = crc8_maxim(&buf[2], 9); // CRC over payload only
          
          // Single Serial.write call
          while (Serial.availableForWrite() < 12) {}
          Serial.write(buf, 12);
          
          // Skip timestamp calculation and normal processing
          channels[i].last_picstop = channels[i].PICstop;
          channels[i].totalize++;
          continue;
        } // end of binary mode
        
        // delta ticks since previous event on this channel
        
        // protect PICstop reads from ISR trips
        int64_t picstop_now64, last_picstop64;
        noInterrupts();
        picstop_now64 = channels[i].PICstop;
        last_picstop64 = channels[i].last_picstop;
        interrupts();
        int64_t dcount = picstop_now64 - last_picstop64;

        // delta_ps = dcount*PICTICK_PS - (int64_t)channels[i].tof + (int64_t)channels[i].last_tof;
        int64_t delta_ps = dcount * (int64_t)PICTICK_PS
                         - (int64_t)channels[i].tof
                         + (int64_t)channels[i].last_tof;

        // Mixed-radix accumulation with automatic carry/borrow
        if (delta_ps >= 0) {
          channels[i].timestamp.picos += (uint64_t)delta_ps;
          if (channels[i].timestamp.picos >= PS_PER_SEC) {
            channels[i].timestamp.picos -= PS_PER_SEC;
            channels[i].timestamp.seconds += 1u;
          }
        } else {
          uint64_t m = (uint64_t)(-delta_ps);
          if (m <= channels[i].timestamp.picos) {
            channels[i].timestamp.picos -= m;
          } else {
            m -= channels[i].timestamp.picos;
            uint64_t borrow_sec = 1 + (m / PS_PER_SEC);
            uint64_t rem = m % PS_PER_SEC;
            channels[i].timestamp.seconds -= (uint32_t)borrow_sec;
            channels[i].timestamp.picos = PS_PER_SEC - rem;
          }
        }

        channels[i].last_picstop = channels[i].PICstop; // Update last_picstop for next calculation
        channels[i].new_ts_ready = 1;
        channels[i].totalize++;    // increment number of events
        channels[i].ready_next();  // Re-arm for next measurement, clear TDC INTB

        /******************************/
        /* Output routines start here */
        /******************************/

        // if poll character is not null, only output if we've received that character via serial
        // NOTE: this may provide random results if measuring timestamp from both channels!
        if ((channels[i].totalize > 2) &&  // throw away first readings
            ((!config.POLL_CHAR) ||        // if unset, output everything
             ((Serial.available() > 0) && (Serial.read() == config.POLL_CHAR)))) {

          switch (config.MODE) {
            case Timestamp: // Defer Timestamp printing to the post-loop pairing block to enforce ordering
              break;

            case Interval: // handled after channel loop (pairing logic)
              break;

            case Period: // Period mode: timestamp(n) - timestamp(n-1) for this channel
              if (channels[i].new_ts_ready) {
                // Calculate period: current timestamp - previous timestamp
                Timestamp64 period = timestamp_difference(&channels[i].timestamp, 
                    &channels[i].last_timestamp);
                {
                  char line[64];
                  print_timestamp(line, sizeof(line), &period, (char)channels[i].name, false);  // No wrap
                }
                channels[i].new_ts_ready = 0;
              }
              break;

            case Hat: // handled after channel loop (pairing logic)
              break;

            case Debug:
              {
                char line[128];
                size_t n = 0;
                
                // Raw TDC7200 values (6 digits each)
                n += sprintf(line + n, "%06lu ", (unsigned long)channels[i].time1Result);
                n += sprintf(line + n, "%06lu ", (unsigned long)channels[i].time2Result);
                n += sprintf(line + n, "%06lu ", (unsigned long)channels[i].clock1Result);
                n += sprintf(line + n, "%06lu ", (unsigned long)channels[i].cal1Result);
                n += sprintf(line + n, "%06lu ", (unsigned long)channels[i].cal2Result);
                
                // Write the line so far
                Serial.write((const uint8_t*)line, n);
                
                // PICstop (int64_t - use new print_int64 function)
                print_int64(channels[i].PICstop, false);
                Serial.write(' ');
                
                // tof (int64_t - use new print_int64 function) 
                print_int64(channels[i].tof, false);
                Serial.write(' ');
                
                // timestamp (no WRAP, PLACES=12) with channel name
                print_timestamp(line, sizeof(line), &channels[i].timestamp, (char)channels[i].name, false);
              }
              break;

            case Null:
              break;
          }  // switch


        }  // print result

      }  // if INTB
    }    // for

    // Timestamp mode: assemble and print pairs without timeout
    if (config.MODE == Timestamp) {
      // Two-slot buffer; accumulate two successive samples (across either channel)
      // then emit exactly two lines per pair in fixed order: if both channels are
      // present print chA then chB; if both are the same channel, print that
      // channel twice.
      struct PairSlot {
        Timestamp64 t;
        uint8_t ch;
      };
      static PairSlot ts_pair[2];
      static uint8_t ts_pair_count = 0;

      // Ingest any fresh samples into the pair buffer
      for (int ci = 0; ci < 2; ++ci) {
        if (channels[ci].new_ts_ready && (channels[ci].totalize > 2)) {
          if (ts_pair_count < 2) {
            ts_pair[ts_pair_count].t = channels[ci].timestamp;
            ts_pair[ts_pair_count].ch = (uint8_t)ci;
            ts_pair_count++;
          }
          channels[ci].new_ts_ready = 0;  // consume
        }
      }

      // If we have a complete pair, emit in fixed order with poll gating
      if (ts_pair_count == 2) {
        bool ok = (!config.POLL_CHAR);
        if (!ok) {
          if ((Serial.available() > 0) && (Serial.read() == config.POLL_CHAR)) ok = true;
        }
        if (ok) {
          // Determine composition and enforce chA then chB order when both present
          if ((ts_pair[0].ch == 0 && ts_pair[1].ch == 1) || (ts_pair[0].ch == 1 && ts_pair[1].ch == 0)) {
            // Mixed channels: find A then B
            const PairSlot *A = (ts_pair[0].ch == 0) ? &ts_pair[0] : &ts_pair[1];
            const PairSlot *B = (ts_pair[0].ch == 1) ? &ts_pair[0] : &ts_pair[1];
            // Print chA timestamp - OPTIMIZED
            {
              char line[64];
              print_timestamp(line, sizeof(line), &A->t, (char)channels[0].name);
            }
            
            // Print chB timestamp
            {
              char line[64];
              print_timestamp(line, sizeof(line), &B->t, (char)channels[1].name);
            }
          } else {
            // Same channel twice: print both with that channel's name
            uint8_t ci = ts_pair[0].ch;
            char cname = channels[ci].name;
            for (int k = 0; k < 2; ++k) {
              char line[64];
              print_timestamp(line, sizeof(line), &ts_pair[k].t, cname);
            }
          }
          ts_pair_count = 0;  // clear pair buffer after printing
        }
      }
    }

    // After processing both channels, pair and print once per matched sample for Interval and 3-Cornered Hat
    if ((channels[0].new_ts_ready && channels[1].new_ts_ready) && (channels[0].totalize > 2) && (channels[1].totalize > 2)) {
      // Optional poll gating
      bool ok = (!config.POLL_CHAR);
      if (!ok) {
        if ((Serial.available() > 0) && (Serial.read() == config.POLL_CHAR)) ok = true;
      }
      if (ok) {
        switch (config.MODE) {
          case Interval:
            {
              // Calculate time interval A->B
              Timestamp64 interval = timestamp_difference(&channels[1].timestamp, &channels[0].timestamp);
              {
                char line[64];
                print_timestamp(line, sizeof(line), &interval, '\0', false);  // No wrap, no channel name
              }
              channels[0].new_ts_ready = 0;
              channels[1].new_ts_ready = 0;
              break;
            }
          case Hat:
            {
              // 3-Cornered Hat mode: chA, chB, and chC (synthesized)
              // chC = int(chB) + (chB - chA) - properly handle negative differences
              
              {
                char line[64];
                print_timestamp(line, sizeof(line), &channels[0].timestamp, (char)channels[0].name);
              }
              {
                char line[64];
                print_timestamp(line, sizeof(line), &channels[1].timestamp, (char)channels[1].name);
              }
              
              // Calculate chC = int(chB) + (chB - chA)
              Timestamp64 interval = timestamp_difference(&channels[1].timestamp, &channels[0].timestamp);
              Timestamp64 chC;
              
              // chC uses the integer seconds from chB, plus the fractional difference
              chC.seconds = channels[1].timestamp.seconds;  // int(chB) - integer seconds from chB
              chC.picos = interval.picos;              // (chB - chA) fractional part
              
              // Handle negative fractional differences (interval.seconds < 0 means negative difference)
              if (interval.seconds < 0) {
                // The fractional part is in complement representation, convert to normal
                if (interval.picos != 0) {
                  chC.picos = PS_PER_SEC - interval.picos;
                  // Since we're subtracting from the integer seconds, borrow if needed
                  chC.seconds -= 1;
                }
              }
              
              // Print chC (synthesized)
              {
                char line[64];
                print_timestamp(line, sizeof(line), &chC, 'C');
              }
              
              channels[0].new_ts_ready = 0;
              channels[1].new_ts_ready = 0;
              break;
            }
          default: break;
        }
      }
    }

    // Check if config was requested during this loop iteration
    if (config_requested) {
      config_requested = 0;  // Clear the flag
      
      // Stop TDC7200 measurements to prevent new data during config
      Serial.println("# Stopping measurements for config...");
      stop_all_measurements();
      
      // Flush any pending measurements from TDC7200 chips to prevent
      // them from appearing after returning from config menu
      Serial.println("# Flushing pending measurements before config...");
      flush_all_channels();
      
      // Small delay to ensure buffer is fully cleared
      delay(10);
      
      // Double-check buffer is clear
      while (Serial.available()) (void)Serial.read();
      
      // Enter config menu directly (no T/P choice needed)
      backup_config();
      show_config_menu();
      handle_config_change_exit();
      
      // Clear any remaining characters after config menu exits
      while (Serial.available()) (void)Serial.read();
      
      // Handle exit from config menu
      // Always handle config changes (whether written to EEPROM or not)
      handle_config_change_exit();
      
      // If restart required, exit loop to reinitialize
      if (config_change_requires_restart()) {
        skip_config_prompt_once = 1;
        just_restarted = 1;  // Set flag for next loop iteration
        return; // reinitialize via ticc_setup() on next loop entry
      }
      
      // Restart measurements after config changes
      Serial.println("# Restarting measurements...");
      start_all_measurements();
      
      // Clear the config_changed flag for next time
      config_changed = 0;
    }

    // Check if restart was requested (option '2' from config menu)
    if (request_restart) {
      request_restart = 0;  // Clear the flag
      just_restarted = 1;   // Set flag for next loop iteration
      Serial.println("# Restart requested, reinitializing system...");
      return;  // Exit loop to trigger fresh ticc_setup() call
    }

  }  // while (1) loop

  Serial.println("# ");
  Serial.println("# Got break character... exiting loop");
  Serial.println("# ");
  delay(100);

}  // main loop()


/****************************************************************
 * Interrupt Service Routines
 ****************************************************************/

// ISR for timer. Capture PICcount on each channel's STOP 0->1 transition.
void coarseTimer() {
  PICcount++;
}

void catch_stop0() {
  channels[0].PICstop = PICcount;
}

void catch_stop1() {
  channels[1].PICstop = PICcount;
}

